# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VIPPattern' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VIPPattern
  pod 'SnapKit'
  pod 'KeychainSwift'
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'

  target 'VIPPatternTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VIPPatternUITests' do
    # Pods for testing
  end

end
